import { StyleSheet } from "react-native";

const createStyles = (isDarkMode, colors) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 45,
      backgroundColor: isDarkMode ? colors.background : "#fff",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    centerTextContainer: {
      flex: 1,
      alignItems: "center",
    },
    rightSection: {
      alignItems: "flex-end",
    },
    profileImage: {
      width: 80,
      height: 80,
      borderRadius: 40,
      marginBottom: 5,
      borderWidth: isDarkMode ? 2 : 0,
      borderColor: isDarkMode ? colors.accent : "transparent",
    },
    profileText: {
      fontSize: 30,
      marginBottom: 10,
      textAlign: "right",
      fontWeight: "bold",
      color: isDarkMode ? colors.text : "#333",
    },
    welcomeText: {
      fontSize: 30,
      marginBottom: 10,
      textAlign: "right",
      fontWeight: "bold",
      color: colors.accent || "#007AFF",
    },
    emailText: {
      fontSize: 14,
      color: isDarkMode ? colors.textSecondary : "gray",
    },
    menuContainer: {
      marginTop: 10,
    },
    menuItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: isDarkMode ? "rgba(255,255,255,0.1)" : "#E5E7EB",
      borderRadius: 24,
      backgroundColor: isDarkMode ? colors.surface : "white",
      width: "100%",
      marginBottom: 10,
    },
    menuText: {
      textAlign: "right",
      fontSize: 16,
      marginLeft: 10,
      flex: 1,
      color: isDarkMode ? colors.text : "#333",
    },
    customSwitch: {
      transform: [{ scaleX: 1.3 }, { scaleY: 1.3 }],
    },
    iconContainer: {
      position: "relative",
    },
    notificationDot: {
      position: "absolute",
      top: -5,
      right: -5,
      backgroundColor: isDarkMode ? colors.accent : "#D72638",
      borderRadius: 10,
      width: 18,
      height: 18,
      justifyContent: "center",
      alignItems: "center",
    },
    profileSection: {
      alignItems: "center",
      paddingVertical: 20,
      backgroundColor: isDarkMode ? colors.surface : "#fff",
      marginHorizontal: 20,
      marginBottom: 20,
      borderRadius: 15,
      shadowColor: isDarkMode ? "#000" : "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0.3 : 0.1,
      shadowRadius: isDarkMode ? 8 : 5,
      elevation: isDarkMode ? 5 : 3,
      borderWidth: isDarkMode ? 1 : 0,
      borderColor: isDarkMode ? "rgba(255,255,255,0.1)" : "transparent",
    },
    profileImageContainer: {
      position: "relative",
      marginBottom: 15,
    },
    cameraButton: {
      position: "absolute",
      bottom: 0,
      right: 0,
      backgroundColor: colors.accent || "#0984e3",
      width: 30,
      height: 30,
      borderRadius: 15,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: isDarkMode ? colors.surface : "#fff",
    },
    profileName: {
      fontSize: 20,
      fontWeight: "bold",
      color: isDarkMode ? colors.text : "#333",
      marginBottom: 5,
    },
    profileEmail: {
      fontSize: 14,
      color: isDarkMode ? colors.textSecondary : "#666",
      marginBottom: 15,
    },
    editProfileButton: {
      backgroundColor: colors.accent || "#f0f0f0",
      paddingVertical: 8,
      paddingHorizontal: 20,
      borderRadius: 20,
    },
    editProfileText: {
      color: isDarkMode ? "#2D3250" : "#fff",
      fontSize: 14,
    },
    settingsSection: {
      backgroundColor: isDarkMode ? colors.surface : "#fff",
      borderRadius: 15,
      padding: 15,
      marginBottom: 20,
      shadowColor: isDarkMode ? "#000" : "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0.3 : 0.1,
      shadowRadius: isDarkMode ? 8 : 5,
      elevation: isDarkMode ? 5 : 3,
      borderWidth: isDarkMode ? 1 : 0,
      borderColor: isDarkMode ? "rgba(255,255,255,0.1)" : "transparent",
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: isDarkMode ? colors.text : "#265CA8",
      marginBottom: 15,
      textAlign: "right",
      ...(isDarkMode && {
        textShadowColor: colors.accent,
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 3,
        opacity: 0.9,
      }),
    },
    settingsItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 7,
      borderBottomWidth: 1,
      borderWidth: 1,
      borderColor: isDarkMode ? "rgba(255,255,255,0.1)" : "#e9e5e5",
      borderRadius: 60,
      marginBottom: 10,
      height: 55,
      backgroundColor: isDarkMode ? colors.surface : "#fff",
    },
    settingsItemIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
    },
    settingsItemContent: {
      flex: 1,
      marginHorizontal: 15,
      alignItems: "flex-end",
    },
    settingsItemTitle: {
      fontSize: 16,
      color: isDarkMode ? colors.text : "#333",
      marginBottom: 3,
    },
    settingsItemDescription: {
      fontSize: 12,
      color: isDarkMode ? colors.textSecondary : "#999",
    },
    settingsItemLeft: {
      alignItems: "flex-start",
      marginLeft: 10,
    },
    languageSelector: {
      flexDirection: "row",
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.08)" : "#f0f0f0",
      borderRadius: 15,
      overflow: "hidden",
    },
    languageOption: {
      paddingVertical: 5,
      paddingHorizontal: 10,
    },
    selectedLanguage: {
      backgroundColor: colors.accent || "#0984e3",
    },
    languageText: {
      fontSize: 12,
      color: isDarkMode ? colors.text : "#666",
    },
    selectedLanguageText: {
      color: isDarkMode ? "#2D3250" : "#fff",
    },
    logoutButton: {
      backgroundColor: colors.accent || "#D72638",
      borderRadius: 12,
      paddingVertical: 15,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 40,
      shadowColor: isDarkMode ? "rgba(255,255,255,0.1)" : "#D72638",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0.2 : 0.3,
      shadowRadius: 5,
      elevation: 3,
    },
    logoutText: {
      color: isDarkMode ? "#2D3250" : "#fff",
      fontSize: 16,
      fontWeight: "bold",
    },
    versionText: {
      textAlign: "center",
      color: isDarkMode ? colors.textSecondary : "#999",
      fontSize: 12,
      marginBottom: 20,
    },
    logoContainer: {
      alignItems: "center",
      marginBottom: 20,
    },
    logo: {
      height: 40,
      width: 175,
    },
    alertModal: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.6)",
    },
    alertContent: {
      backgroundColor: "white",
      borderRadius: 25,
      padding: 20,
      alignItems: "center",
      width: "80%",
      maxWidth: 350,
    },
    alertIconContainer: {
      width: 70,
      height: 70,
      borderRadius: 35,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 15,
    },
    alertTitle: {
      fontSize: 20,
      fontWeight: "700",
      marginBottom: 10,
      textAlign: "center",
    },
    alertMessage: {
      fontSize: 16,
      textAlign: "center",
      marginBottom: 20,
      paddingHorizontal: 10,
    },
    alertButton: {
      paddingVertical: 10,
      paddingHorizontal: 25,
      borderRadius: 12,
      marginTop: 10,
    },
    alertButtonText: {
      color: "white",
      fontSize: 16,
      fontWeight: "600",
    },
    alertButtonsContainer: {
      flexDirection: "row",
      justifyContent: "center",
      marginTop: 20,
    },
  });
};

export default createStyles;
